### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by ankurbag** [ankurbag/INFO6205_06#1]
## TO-DO List
- [x] Study Genetic Algorithm
    - [x] Travelling Salesman Problem - http://www.baeldung.com/java-simulated-annealing-for-traveling-salesman
    - [x] https://github.com/Apress/genetic-algorithms-in-java-basics
    - [x] http://www.theprojectspot.com/tutorial-post/creating-a-genetic-algorithm-for-beginners/3
    - [x] https://stackoverflow.com/questions/1575061/ga-written-in-java

- [x] Decide Problem to be solved 
    - [x] https://en.wikipedia.org/wiki/List_of_genetic_algorithm_applications
    - [x] https://www.brainz.org/15-real-world-applications-genetic-algorithms
    - [x] Consensus Algorithm
    - [x] Maze Runner
    - [x] Class Scheduler  https://www.codeproject.com/Articles/23111/Making-a-Class-Schedule-Using-a-Genetic-Algorithm
http://ieeexplore.ieee.org/document/1225396/?reload=true
http://choonsiong.com/public/books/Algorithm/Genetic%20Algorithms%20in%20Java%20Basics.pdf
    - [x] Cryptocurrency
    - [x] Image processing
    - [x] Trading Simulator https://www.investopedia.com/articles/financial-theory/11/using-genetic-algorithms-forecast-financial-markets.asp
    - [x] Evolve Sentence https://www.youtube.com/watch?v=p637zWPXAAk&index=6&list=PLiWcnsSmNaTcyR8-F3L4TZjMM1bDHKvw9
    
 - [x] Tentative Plan
    - [x] GA Framework
    - [x] Finalize problems - Class Scheduler
    - [x] Decide Use case
    - [x] UI / BOT
